# Generated by Django 5.1 on 2024-08-27 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
