# Generated by Django 5.1 on 2024-08-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_acceleration_sensor3_sensordata_acceleration_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='acceleration_x',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='acceleration_y',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='acceleration_z',
        ),
    ]
